# Generated by Django 5.2.11 on 2026-03-28 10:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_alter_paymenttransaction_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=32)),
                ('shipping_country', models.CharField(max_length=120)),
                ('shipping_address', models.CharField(max_length=240)),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_postal_code', models.CharField(max_length=40)),
                ('billing_same_as_shipping', models.BooleanField(default=True)),
                ('billing_country', models.CharField(blank=True, default='', max_length=120)),
                ('billing_address', models.CharField(blank=True, default='', max_length=240)),
                ('billing_city', models.CharField(blank=True, default='', max_length=120)),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=40)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order_items', to='users.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='paystack', max_length=24)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_minor', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='initialized', max_length=16)),
                ('authorization_url', models.URLField(blank=True, default='', max_length=1000)),
                ('access_code', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_initialize_response', models.JSONField(blank=True, default=dict)),
                ('gateway_verify_response', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['order', 'created_at'], name='payments_pa_order_i_4d9364_idx')],
            },
        ),
    ]
