# Generated by Django 5.2.11 on 2026-03-11 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('short_bio', models.CharField(blank=True, default='', max_length=280)),
                ('profile_image_url', models.URLField(blank=True, default='')),
                ('hero_image_url', models.URLField(blank=True, default='')),
                ('selected_theme', models.CharField(blank=True, default='minimal-light', max_length=64)),
                ('name_font', models.CharField(blank=True, default='Inter, sans-serif', max_length=120)),
                ('name_color', models.CharField(blank=True, default='#223136', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
