# Generated by Django 5.2.11 on 2026-03-14 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercontactlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upload', 'Upload'), ('social', 'Social')], default='upload', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('image_url', models.URLField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('embed_html', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=280)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
