# Generated by Django 5.2.11 on 2026-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_productgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappearance',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='appearance/hero/'),
        ),
        migrations.AddField(
            model_name='userappearance',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='appearance/profile/'),
        ),
    ]
