# Generated by Django 5.2.11 on 2026-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userappearance_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(default='manual', max_length=24),
        ),
    ]
