from django.urls import path

from .views import (
    CartItemDetailView,
    CartMergeView,
    CartView,
    CheckoutInitializeView,
    CheckoutVerifyView,
    DashboardSummaryView,
    DashboardTimeseriesView,
    DashboardTrackEventView,
    GoogleAuthView,
    MeView,
    PublicContactLeadSubmitView,
    PaystackWebhookView,
    ProductListView,
    UserAppearanceView,
    UserAppearanceImageUploadView,
    UserContactLeadDetailView,
    AdminDatabaseExportView,
    AdminDatabaseImportView,
    UserDataExportView,
    UserContactLeadsView,
    UserLinkDetailView,
    UserLinksView,
    UserPortfolioItemDetailView,
    UserPortfolioItemsView,
    UserPortfolioUploadView,
    PublicProfileView,
    PublicTrackEventView,
    SetUsernameView,
    UsernameAvailabilityView,
    UserPortfolioImportImagesView,
)


urlpatterns = [
    path("auth/google/", GoogleAuthView.as_view(), name="auth-google"),
    path("users/me/", MeView.as_view(), name="users-me"),
    path("users/check-username/", UsernameAvailabilityView.as_view(), name="users-check-username"),
    path("users/set-username/", SetUsernameView.as_view(), name="users-set-username"),
    path("users/appearance/", UserAppearanceView.as_view(), name="users-appearance"),
    path("users/appearance/upload-image/", UserAppearanceImageUploadView.as_view(), name="users-appearance-upload-image"),
    path("users/links/", UserLinksView.as_view(), name="users-links"),
    path("users/links/<int:link_id>/", UserLinkDetailView.as_view(), name="users-link-detail"),
    path("users/portfolio/", UserPortfolioItemsView.as_view(), name="users-portfolio"),
    path("users/portfolio/upload/", UserPortfolioUploadView.as_view(), name="users-portfolio-upload"),
    path("users/portfolio/import-images/", UserPortfolioImportImagesView.as_view(), name="users-portfolio-import-images"),
    path("users/portfolio/<int:item_id>/", UserPortfolioItemDetailView.as_view(), name="users-portfolio-detail"),
    path("users/contacts/", UserContactLeadsView.as_view(), name="users-contacts"),
    path("users/contacts/<int:lead_id>/", UserContactLeadDetailView.as_view(), name="users-contact-detail"),
    path("users/export/", UserDataExportView.as_view(), name="users-export"),
    path("admin/export/full/", AdminDatabaseExportView.as_view(), name="admin-export-full"),
    path("admin/import/full/", AdminDatabaseImportView.as_view(), name="admin-import-full"),
    path("public/profile/", PublicProfileView.as_view(), name="public-profile"),
    path("public/track/", PublicTrackEventView.as_view(), name="public-track"),
    path("public/contacts/", PublicContactLeadSubmitView.as_view(), name="public-contacts"),
    path("products/", ProductListView.as_view(), name="products-list"),
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/items/<int:item_id>/", CartItemDetailView.as_view(), name="cart-item-detail"),
    path("cart/merge/", CartMergeView.as_view(), name="cart-merge"),
    path("checkout/initialize/", CheckoutInitializeView.as_view(), name="checkout-initialize"),
    path("checkout/verify/", CheckoutVerifyView.as_view(), name="checkout-verify"),
    path("payments/paystack/webhook/", PaystackWebhookView.as_view(), name="paystack-webhook"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("dashboard/timeseries/", DashboardTimeseriesView.as_view(), name="dashboard-timeseries"),
    path("dashboard/track/", DashboardTrackEventView.as_view(), name="dashboard-track"),
]
